# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
    
    # Cache derived data to speed up subsequent builds
    - name: Cache Xcode derived data
      uses: actions/cache@v3
      with:
        path: ~/Library/Developer/Xcode/DerivedData
        key: derived-data-$(date +%Y%m%d%H%M)

    - name: Build HitHappens project
      run: xcodebuild build -project HitHappens.xcodeproj -scheme "HitHappens Dev" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO

    # Uncomment the following steps to run tests if needed
    # - name: Run tests
    #   run: xcodebuild test -project HitHappens.xcodeproj -scheme "HitHappens Dev" CODE_SIGNING_ALLOWED=NO CODE_SIGNING_REQUIRED=NO
