# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
#    branches: [ "main", "dev*", "^dev"]
    branches: [ "^dev"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get swift version
      run: swift --version 
    - name: Build
      run: ./Source/Scripts/github_workflow_v1.sh
      #run: swift build
    - name: Run tests
      run: swift test
