# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "dev/V1.5.0", "dev/V1.6.0", "dev/V1.5.7", "dev/V1.8.0"]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get swift version
      run: swift --version 
    - name: Build
      run: ./Source/Scripts/github_workflow_v1.sh
    #- name: Run tests
    #run: swift test
    
  #publish:
  #  needs: [build]
  #  runs-on: ubuntu-latest
  #  environment: production
  #  steps:
  #    - name: publish
  #      echo 'publishing'
